db_location: 'test.db'
group_templates:
  - name: 'Default'
    description: 'Use MinHashLSH to find groups with a Jaccard similarity of 1.'
    index_type: 'minhashlsh'
    threshold: 1.0
    case_sensitive: false
    use_shingles: false
    shingle_length: 4
    num_permutations: 128